GET http://localhost:8080/employees/

###
POST http://localhost:8080/employees/
Content-Type: application/json

{
  "name": "Robert Downey Jr.",
  "level": "Senior",
  "position": "Sidekick"
}

###
DELETE http://localhost:8080/employees/6332ccb3b37ae77f5b12a1b5

###
PATCH http://localhost:8080/employees/6332cd97d8efbe310173ad4c
Content-Type:  application/json

{
  "level": "Super Expert"
}
