GET http://localhost:8080/api/employees/

###
POST http://localhost:8080/api/employees/641068af72d6d2a205c712e4/kittens
Content-Type: application/json

{
  "name": "Jordin",
  "img": "https://cdn2.thecatapi.com/images/ad1.jpg",
  "age": 5
}

###
DELETE http://localhost:8080/api/employees/63fc6e4bca1cb463caa21779

###
PATCH http://localhost:8080/api/employees/63fc6e4bca1cb463caa21779
Content-Type:  application/json

{
  "name": "asd"
}
