GET http://localhost:8080/api/employees/63bd59c2ed10eb9eab30be31/equipments/

###
POST http://localhost:8080/api/equipments/
Content-Type: application/json

{
  "name": "IPhone X",
  "type": "Phone",
  "price": 8000,
  "employee": "63bd59c2ed10eb9eab30be31"
}

###
POST http://localhost:8080/api/employees/
Content-Type: application/json

{
  "name": "Valaki",
  "level": "Godlike",
  "position": "Joker"
}

###
DELETE http://localhost:8080/api/employees/63fc6e4bca1cb463caa21779

###
PATCH http://localhost:8080/api/employees/63fc6e4bca1cb463caa21779
Content-Type:  application/json

{
  "name": "asd"
}
